# Generated by Django 3.1.7 on 2021-04-18 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('MAN', '男性'), ('WOMAN', '女性')], default='MAN', max_length=5, verbose_name='性别')),
                ('phone_number', models.CharField(max_length=255, verbose_name='电话号码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('address', models.CharField(max_length=255, verbose_name='家庭住址')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick_cause', models.CharField(max_length=255, verbose_name='病因')),
                ('symptom', models.TextField(verbose_name='症状')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='看病医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient', verbose_name='病人')),
            ],
        ),
    ]
